# Generated by Django 5.0.6 on 2026-05-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('activity_type', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('co2e', models.FloatField()),
                ('is_suspicious', models.BooleanField(default=False)),
                ('review_status', models.CharField(default='PENDING', max_length=20)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
